version: "2"
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
    env_file: /opt/redash/env
  scheduler:
    <<: *redash-service
    command: scheduler
    env_file: /opt/redash/env
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    env_file: /opt/redash/env
    #environment:
    #  QUEUES: "scheduled_queries,schemas"
    #  WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    env_file: /opt/redash/env
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
    env_file: /opt/redash/env
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.6-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    env_file: /opt/redash/env
    ports:
      - "8088:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always